# Generated by Django 3.0.8 on 2020-09-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=60, verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(default='blankref', max_length=20, unique=True, verbose_name='артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(blank=True, max_length=80, verbose_name='форма'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='размер'),
            preserve_default=False,
        ),
    ]
